/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyReviewAutoOpenPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  diaryFolderPath: "\u65E5\u8BB0",
  enabled: true
};
var DailyReviewAutoOpenPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new DailyReviewSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.enabled) {
        this.openRandomDiary();
      }
    });
    console.log("Daily Review Auto Open plugin loaded");
  }
  onunload() {
    console.log("Daily Review Auto Open plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openRandomDiary() {
    const { diaryFolderPath } = this.settings;
    const diaryFolder = this.app.vault.getAbstractFileByPath(diaryFolderPath);
    if (!(diaryFolder instanceof import_obsidian.TFolder)) {
      console.warn(`Diary folder not found: ${diaryFolderPath}`);
      return;
    }
    const markdownFiles = diaryFolder.children.filter(
      (file) => file instanceof import_obsidian.TFile && file.extension === "md"
    );
    if (markdownFiles.length === 0) {
      console.warn("No markdown files found in diary folder");
      return;
    }
    const randomFile = markdownFiles[Math.floor(Math.random() * markdownFiles.length)];
    await this.app.workspace.openLinkText(randomFile.path, "", true);
    console.log(`Opened random diary: ${randomFile.path}`);
  }
};
var DailyReviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable auto open").setDesc("Automatically open a random diary entry when Obsidian starts").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Diary folder path").setDesc("Path to the folder containing your diary entries").addText((text) => text.setPlaceholder("\u65E5\u8BB0").setValue(this.plugin.settings.diaryFolderPath).onChange(async (value) => {
      this.plugin.settings.diaryFolderPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
