/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyReviewAutoOpenPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  diaryFolderPath: "\u65E5\u8BB0",
  diaryFolderPaths: ["\u65E5\u8BB0"],
  // 默认包含日记文件夹
  enabled: true,
  recentHistorySize: 3,
  // 默认记住最近3篇日记
  recentlyOpened: []
  // 默认为空数组
};
var DailyReviewAutoOpenPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new DailyReviewSettingTab(this.app, this));
    this.addCommand({
      id: "open-random-diary",
      name: "\u6253\u5F00\u968F\u673A\u65E5\u8BB0",
      callback: () => {
        void this.openRandomDiary();
      }
    });
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.enabled) {
        void this.openRandomDiary();
      }
    });
    console.debug("Daily Review Auto Open plugin loaded");
  }
  onunload() {
    console.debug("Daily Review Auto Open plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings.diaryFolderPaths.length === 1 && this.settings.diaryFolderPaths[0] === "\u65E5\u8BB0" && this.settings.diaryFolderPath !== "\u65E5\u8BB0") {
      this.settings.diaryFolderPaths = [this.settings.diaryFolderPath];
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openRandomDiary() {
    const { diaryFolderPaths, recentlyOpened, recentHistorySize } = this.settings;
    if (!diaryFolderPaths || diaryFolderPaths.length === 0) {
      console.warn("No diary folders configured");
      return;
    }
    const validFolders = [];
    for (const path of diaryFolderPaths) {
      const folder = this.app.vault.getAbstractFileByPath(path);
      if (folder instanceof import_obsidian.TFolder) {
        validFolders.push(folder);
      } else {
        console.warn(`Diary folder not found: ${path}`);
      }
    }
    if (validFolders.length === 0) {
      console.warn("No valid diary folders found");
      return;
    }
    const selectedFolder = validFolders[Math.floor(Math.random() * validFolders.length)];
    console.debug(`Selected folder: ${selectedFolder.path}`);
    const markdownFiles = selectedFolder.children.filter(
      (file) => file instanceof import_obsidian.TFile && file.extension === "md"
    );
    if (markdownFiles.length === 0) {
      console.warn(`No markdown files found in folder: ${selectedFolder.path}`);
      return;
    }
    const availableFiles = markdownFiles.filter(
      (file) => !recentlyOpened.includes(file.path)
    );
    if (availableFiles.length === 0) {
      console.debug("All diaries have been opened recently, clearing history");
      this.settings.recentlyOpened = [];
    }
    const finalFiles = availableFiles.length > 0 ? availableFiles : markdownFiles;
    const randomFile = finalFiles[Math.floor(Math.random() * finalFiles.length)];
    await this.app.workspace.openLinkText(randomFile.path, "", true);
    console.debug(`Opened random diary: ${randomFile.path}`);
    this.addToRecentlyOpened(randomFile.path);
  }
  /**
   * 将日记路径添加到最近打开列表
   * 保持列表长度不超过 recentHistorySize
   */
  async addToRecentlyOpened(filePath) {
    const { recentlyOpened, recentHistorySize } = this.settings;
    const index = recentlyOpened.indexOf(filePath);
    if (index > -1) {
      recentlyOpened.splice(index, 1);
    }
    recentlyOpened.unshift(filePath);
    if (recentlyOpened.length > recentHistorySize) {
      recentlyOpened.length = recentHistorySize;
    }
    await this.saveSettings();
  }
};
var DailyReviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * 获取根目录下的所有用户文件夹（排除系统文件夹）
   * 按字母顺序排序
   */
  getRootFolders() {
    const allFiles = this.app.vault.getAllLoadedFiles();
    const configDir = this.app.vault.configDir;
    const rootFolders = allFiles.filter((file) => file instanceof import_obsidian.TFolder).filter((folder) => {
      const isRootFolder = !folder.path.includes("/");
      const isSystemFolder = folder.path.startsWith(configDir) || folder.path.startsWith(".trash") || folder.path.startsWith(".git");
      return isRootFolder && !isSystemFolder;
    }).map((folder) => folder.path).sort();
    return rootFolders;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable auto open").setDesc("Automatically open a random diary entry when Obsidian starts").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Diary folders").setHeading();
    const rootFolders = this.getRootFolders();
    if (rootFolders.length === 0) {
      new import_obsidian.Setting(containerEl).setName("No folders found").setDesc("No user folders found in the root directory");
    } else {
      rootFolders.forEach((folderPath) => {
        new import_obsidian.Setting(containerEl).setName(folderPath).setDesc("Include this folder in random selection").addToggle(
          (toggle) => toggle.setValue(this.plugin.settings.diaryFolderPaths.includes(folderPath)).onChange(async (value) => {
            if (value) {
              if (!this.plugin.settings.diaryFolderPaths.includes(folderPath)) {
                this.plugin.settings.diaryFolderPaths.push(folderPath);
              }
            } else {
              this.plugin.settings.diaryFolderPaths = this.plugin.settings.diaryFolderPaths.filter((p) => p !== folderPath);
            }
            await this.plugin.saveSettings();
          })
        );
      });
    }
    new import_obsidian.Setting(containerEl).setName("History settings").setHeading();
    new import_obsidian.Setting(containerEl).setName("Recent history size").setDesc("Remember recently opened diaries to avoid repetition").addSlider((slider) => slider.setLimits(0, 15, 1).setValue(this.plugin.settings.recentHistorySize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.recentHistorySize = value;
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.recentlyOpened.length > 0) {
      new import_obsidian.Setting(containerEl).setName("Recently opened diaries").setDesc("Diaries opened in recent sessions").then((setting) => {
        const historyText = this.plugin.settings.recentlyOpened.map((path) => {
          const parts = path.split("/");
          return parts[parts.length - 1];
        }).join(", ");
        setting.descEl.createEl("div", {
          text: historyText || "No recent history",
          cls: "setting-item-description"
        });
      });
      new import_obsidian.Setting(containerEl).setName("Clear history").setDesc("Clear the history of recently opened diaries").addButton((button) => button.setButtonText("Clear").setClass("mod-warning").onClick(async () => {
        this.plugin.settings.recentlyOpened = [];
        await this.plugin.saveSettings();
        this.display();
      }));
    }
  }
};
